### ISSUE TITLE
Unhandled 'error' event when running `yarn run haul start -- --platform ios`

### ISSUE THREAD

**Issue by lucqui** [callstack-io/haul#77]
### Current Behavior
I get the error when running `yarn run haul start -- --platform ios`

events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:8081
    at Object.exports._errnoException (util.js:1034:11)
    at exports._exceptionWithHostPort (util.js:1057:20)
    at Server._listen2 (net.js:1265:14)
    at listen (net.js:1301:10)
    at doListening (net.js:1416:7)
    at _combinedTickCallback (internal/process/next_tick.js:83:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
error Command failed with exit code 1.

### Expected Behavior
It should run w/o errors.

### Haul Configuration (webpack.haul.js)
module.exports = ({ platform }) => ({
  entry: `./index.${platform}.js`,
});

### Your Environment
I'm running on a macbook and trying to run this react-native + redux project. 

| software         | version
| ---------------- | -------
| Haul             |  0.21.3
| react-native     | 0.42.3 (2.0.1 for the react-native-cli)
| node             | v7.8.0
| npm or yarn      | 4.2.0 (0.21.3 for yarn)

**Comment by satya164** [comment]
Something else is running on the same port. Check for other instances of React Native packager or Haul running in another Terminal.

**Comment by skellock** [comment]
`EADDRINUSE 127.0.0.1:8081` probably means your react-native packager is running.  Have a look through your open terminal windows.  If you can't find it and you're still angry, `sudo lsof -i :8081` and `kill -9 <pid>` will teach it a lesson.
